Qiskit/web-components

.gitignore, .storybook/main.js, components/banner/index.scss, components/banner/index.ts, components/banner/package.json, components/banner/tsconfig.json, components/rollup.config.js, components/scss.d.ts, package.json, wds-base.config.js, yarn.lock
=> Setup PostCSS to import styles from .scss

.changeset/poor-llamas-sing.md, components/banner/index.scss, components/banner/package.json, yarn.lock
Now using the Carbon styles from SCSS.
=> Update banner styles to match the design system

.changeset/rich-meals-look.md, components/banner/package.json, package-lock.json
=> Update to Lit v2

.storybook/main.js, components/banner/index.scss, components/navbar/index.scss, package-lock.json, package.json, rollup.config.js, wds-base.config.js
Thanks to @bennypowers for the plugin and the support!
=> Replace `rollup-plugin-postcss-lit` with `rollup-plugin-lit-css`

.github/workflows/codeql-analysis.yml
This PR add the CodeQL workflow for code scanning.
=> ci: add code scanning

.github/workflows/deploy.yml, .github/workflows/release.yml
Related with: https://github.com/Qiskit/qiskit.org/issues/2363
=> Replace `qiskit-community` links with `Qiskit`

.changeset/rude-spies-brush.md, package.json
=> Remove the mandatory Node v16

.github/pull_request_template.md
Created a pull request template.
Closes #61
The file name and location follows the guide in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository.
=> feat: create pull request template

.changeset/mega-menu-added.md
After see this PR: https://github.com/Qiskit/web-components/pull/83
Change MegaMenuDropdown addition as minor version.
=> Change MegaMenuDropdown addition as minor version

.changeset/cuddly-llamas-rescue.md, components/mega-menu-dropdown/index.stories.ts, components/mega-menu-dropdown/index.ts, components/navbar/README.md
Fix the QiskitMegaMenuDropdown name
=> Fix the QiskitMegaMenuDropdown name

.changeset/readme-additions.md, README.md, components/mega-menu-dropdown/README.md
Added Readme for MegaMenuDropdown
Improved Readme in the root.
=> Add Readme

.changeset/curly-needles-call.md, components/mega-menu-dropdown/index.scss
Added a variable for the input filter background color
=> Added a variable for the input filter background color

.changeset/yellow-sloths-do.md, components/mega-menu-dropdown/index.scss
Simplify the MegaMenuDropdown custom properties
=> Simplify the MegaMenuDropdown custom properties

.changeset/loud-countries-train.md, components/mega-menu-dropdown/index.test.ts
Adds test to the mega menu dropdown component
=> Added test to mmd component

.github/ISSUE_TEMPLATE/feature_request.yml
Related to Qiskit/qiskit.org#2679
As requested in https://github.com/Qiskit/qiskit.org/issues/2679
=> docs: remove field from "feature" template

.changeset/wicked-ads-cover.md, components/column-list/index.stories.ts, components/column-list/index.ts, components/footer/index.ts, components/mega-menu-dropdown/index.scss, components/mega-menu-dropdown/index.ts
Add missed interfaces
Also add missed namespace to internal column-list component
=> Add missed interfaces

.changeset/rotten-waves-train.md, components/ui-shell/header/header-menu-item-mega.ts, components/ui-shell/index.scss, components/ui-shell/index.ts, components/ui-shell/settings.ts
- Adds social media icon links to mobile sidenav.
- Smallest breakpoint sidenav will take full screen width, tablet view will maintain max-width defined by carbon ui-shell
- Adds `Ecosystem` nav item to Community dropdown
- Fixes small classname typo `accout` -> `account`
- Includes small style update to ensure there the header content has a max width to be flush with page content on qiskit.org
Followed similar styles to what was previously implemented in [navbar](https://github.com/Qiskit/web-components/tree/3671dd9d8c6f2da8eafeb093b905bf2f48565b43/components/navbar)
https://user-images.githubusercontent.com/8097306/189445937-5380f2c9-c977-47f0-8860-0c029ddb7704.mov
=> feat(ui-shell): mobile nav enhacements

.changeset/tasty-spoons-serve.md, components/ui-shell/index.scss, components/ui-shell/index.stories.ts
=> Add space before the content

components/ui-shell/header/index.ts, components/ui-shell/index.scss, components/ui-shell/settings.ts, package-lock.json, package.json
=> Small repo fixes

.changeset/update_top_menu_links_201.md, components/footer/index.ts, components/ui-shell/settings.ts
- Update "Qiskit IBM Provider" link to https://qiskit.org/documentation/partners/qiskit_ibm_provider/ (Closes #196)
- Update Slack invite link to https://qisk.it/join-slack (Closes #200)
=> Update top menu links

.changeset/rude-otters-cheat.md, components/ui-shell/settings.ts
This PR removes the "Overview" link from the UI Shell component.
=> feat(ui-shell): remove "Overview" link

.changeset/brave-beds-beg.md
This PR bumps the version for get a new release.
=> chore: version bump

.changeset/three-parents-boil.md, components/ui-shell/index.scss, components/ui-shell/settings.ts
This PR removes the old "Providers" links from the UI Shell component and adds the new "Providers" link.
=> feat(ui-shell): add "Providers" link

.changeset/update-top-nav-bar-links-order.md, components/ui-shell/settings.ts
From Learn, Community, Documentation, Providers to Documentation, Providers, Community, Learn.
This closes #228
=> Change order of top nav-bar links

.changeset/early-pumpkins-explain.md, components/ui-shell/settings.ts
After the migration qiskit-terra -> qiskit he API Reference link has change, so we need to update it
=> Update API Reference link
